<?php
require_once __DIR__.'/config/config.php';
$slug=trim($_GET['slug']??'');
$s=db()->prepare("SELECT s.*,c.name category FROM stories s LEFT JOIN categories c ON c.id=s.category_id WHERE s.slug=? AND s.status='PUBLISHED' LIMIT 1");$s->execute([$slug]);$story=$s->fetch();
if(!$story){http_response_code(404);exit('Story not found.');}
$storyPath='/story/'.rawurlencode((string)$story['slug']);
$shareUrl=absolute_url($storyPath);
$shareText=$story['title'].' '.$shareUrl;
$shareImage=absolute_url('/story-image/'.rawurlencode((string)$story['slug']).'.png?v='.rawurlencode((string)strtotime((string)$story['updated_at'])));
$shareDescription=trim((string)($story['summary']?:$story['impact']?:mb_substr(strip_tags((string)$story['content']),0,260)));
$shareDescription=mb_substr($shareDescription,0,160);
$paragraphs=preg_split("/\R{2,}/",trim($story['content']));
$gallery=[];$structuredSources=[];$correctionNoticeKey='correction_report_submitted_'.(int)$story['id'];$correctionSent=!empty($_SESSION[$correctionNoticeKey]);unset($_SESSION[$correctionNoticeKey]);
try{$g=db()->prepare('SELECT * FROM story_images WHERE story_id=? ORDER BY sort_order,id');$g->execute([$story['id']]);$gallery=$g->fetchAll();$src=db()->prepare('SELECT * FROM story_sources WHERE story_id=? ORDER BY id');$src->execute([$story['id']]);$structuredSources=$src->fetchAll();track_event('view',(int)$story['id']);}catch(Throwable $e){}
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['correction_message'])){verify_csrf();$message=trim($_POST['correction_message']);if($message!==''){try{$r=db()->prepare('INSERT INTO correction_reports(story_id,name,email,message) VALUES(?,?,?,?)');$r->execute([(int)$story['id'],trim($_POST['correction_name']??''),trim($_POST['correction_email']??''),$message]);$_SESSION[$correctionNoticeKey]=true;redirect($storyPath.'#correction');}catch(Throwable $e){}}}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($story['title'])?> — Nepal Disaster Archive</title><meta name="description" content="<?=e($shareDescription)?>"><link rel="canonical" href="<?=e($shareUrl)?>"><meta property="og:type" content="article"><meta property="og:site_name" content="Nepal Disaster Archive"><meta property="og:title" content="<?=e($story['title'])?>"><meta property="og:description" content="<?=e($shareDescription)?>"><meta property="og:url" content="<?=e($shareUrl)?>"><meta property="og:image" content="<?=e($shareImage)?>"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:type" content="image/png"><meta property="og:image:alt" content="<?=e($story['title'].' — Nepal Disaster Archive')?>"><meta name="twitter:card" content="<?=$shareImage?'summary_large_image':'summary'?>"><meta name="twitter:title" content="<?=e($story['title'])?>"><meta name="twitter:description" content="<?=e($shareDescription)?>"><script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'Article','headline'=>$story['title'],'description'=>$shareDescription,'mainEntityOfPage'=>$shareUrl,'publisher'=>['@type'=>'Organization','name'=>'Nepal Disaster Archive'],'inLanguage'=>'en','dateModified'=>date(DATE_W3C,strtotime((string)$story['updated_at']))],JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_THROW_ON_ERROR)?></script><?php if($shareImage):?><meta name="twitter:image" content="<?=e($shareImage)?>"><?php endif;?>
<style>body{margin:0;background:#f7f3ed;color:#17202a;font-family:Georgia,serif}.nav{position:sticky;top:0;background:#111820;color:#fff;z-index:10;padding:15px 5%;display:flex;align-items:center;gap:25px;font-family:Arial}.nav a{color:#fff;text-decoration:none;font-size:13px}.logo{font-weight:900;letter-spacing:2px}.navlinks{margin-left:auto;display:flex;gap:18px}.article{max-width:850px;margin:70px auto;padding:0 25px}.meta{color:#9e2b25;font:800 13px Arial;text-transform:uppercase;letter-spacing:1px}.article h1{font-size:clamp(42px,7vw,72px);line-height:1;margin:15px 0}.dek{font-size:21px;color:#555;line-height:1.6}.facts{display:flex;flex-wrap:wrap;gap:12px;margin:30px 0}.fact{background:#fff;border:1px solid #ddd0c5;padding:15px;border-radius:8px;font-family:Arial}.fact b{display:block;font-size:12px;color:#777}.body{font-size:19px;line-height:1.85}.body p{margin:0 0 24px}.sources{border-top:2px solid #9e2b25;margin-top:45px;padding-top:20px;font:15px Arial;white-space:pre-line;color:#555}.share-tools{display:flex;flex-wrap:wrap;gap:10px;margin:25px 0 35px;font-family:Arial}.share-tools button,.share-tools a{border:1px solid #cfc4b8;background:#fff;color:#17202a;border-radius:6px;padding:10px 13px;font:700 13px Arial;text-decoration:none;cursor:pointer}.share-tools button:hover,.share-tools a:hover{background:#9e2b25;border-color:#9e2b25;color:#fff}.footer{background:#111820;color:#d8dde0;padding:45px 7%;font-family:Arial}.social-links{display:flex;gap:14px;margin-top:20px}.social-links a{display:inline-flex;width:38px;height:38px;align-items:center;justify-content:center;border:1px solid #59636a;border-radius:50%;color:#fff}.social-links a:hover{background:#9e2b25;border-color:#9e2b25}.social-links svg{width:19px;height:19px;fill:currentColor;stroke:currentColor;stroke-width:1.5}.social-links svg rect,.social-links svg circle{fill:none}.social-links svg .icon-fill{fill:currentColor;stroke:none}.story-cover{display:block;width:100%;max-height:520px;object-fit:cover;border-radius:8px;margin-bottom:30px}@media(max-width:850px){.navlinks{display:none}}@media print{@page{margin:18mm}body{background:#fff;color:#111}.public-nav,.share-tools,.correction,.footer .social-links{display:none!important}.article{max-width:none;margin:0;padding:0}.article h1{font-size:30pt}.dek{font-size:14pt;color:#333}.body{font-size:11pt;line-height:1.6}.body p,.fact,.story-cover,figure,.sources{break-inside:avoid;page-break-inside:avoid}.facts{gap:6px}.fact{background:#fff;padding:8px}.story-cover{max-height:180mm;object-fit:contain;margin:15px auto}.sources a{color:#111;text-decoration:none}.footer{margin-top:20mm;padding:8mm 0;color:#111;background:#fff;border-top:1px solid #777}.footer strong{color:#111}}</style></head><body>
<?php require_once __DIR__ . '/includes/public-nav.php'; ?><article class="article"><div class="meta"><?=e($story['category']??'Natural Disaster')?> · <?=e($story['year_label'])?></div><h1><?=e($story['title'])?></h1><p class="dek"><?=e($story['summary'])?></p>
<div class="share-tools" aria-label="Story sharing and download tools"><a href="https://wa.me/?text=<?=e(rawurlencode($shareText))?>" target="_blank" rel="noopener noreferrer">WhatsApp</a><a href="https://www.facebook.com/sharer/sharer.php?u=<?=e(rawurlencode($shareUrl))?>" target="_blank" rel="noopener noreferrer">Facebook</a><a href="mailto:?subject=<?=e(rawurlencode($story['title']))?>&amp;body=<?=e(rawurlencode("Read this story from Nepal Disaster Archive:\n\n".$shareUrl))?>">Email</a><button type="button" id="copy-link">Copy link</button><button type="button" onclick="window.print()">Print / Save as PDF</button></div>
<div class="facts"><?php foreach([['Date',$story['event_date']],['Location',$story['location']],['Magnitude',$story['magnitude']],['Deaths',$story['deaths']],['Injuries',$story['injuries']]] as $f):if($f[1]):?><div class="fact"><b><?=e($f[0])?></b><?=e($f[1])?></div><?php endif;endforeach;?></div>
<div class="body"><?php foreach($paragraphs as $p):?><p><?=nl2br(e($p))?></p><?php endforeach;?></div>
<?php if($story['impact']):?><h2>Impact</h2><div class="body"><p><?=nl2br(e($story['impact']))?></p></div><?php endif;?>
<?php if($structuredSources):?><div class="sources"><strong>Verified sources</strong><?php foreach($structuredSources as $source):?><p><a href="<?=e($source['url']??'')?>" target="_blank" rel="noopener noreferrer"><?=e($source['title'])?></a><?php if($source['publisher']):?> · <?=e($source['publisher'])?><?php endif;?><?php if($source['verified']):?> · Verified<?php endif;?></p><?php endforeach;?></div><?php endif;?>
<?php if($gallery):?><div class="gallery"><?php foreach($gallery as $image):?><figure><img src="<?=BASE_URL?>/<?=e($image['image_path'])?>" alt="<?=e($image['caption']?:$story['title'])?>"><figcaption><?=e($image['caption']??'')?> <?php if($image['credit']):?><small><?=e($image['credit'])?></small><?php endif;?></figcaption></figure><?php endforeach;?></div><?php endif;?>
<section class="correction" id="correction"><h2>Report a correction</h2><?php if($correctionSent):?><p>Thank you. Your correction has been submitted for review.</p><?php else:?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input name="correction_name" placeholder="Your name"><input type="email" name="correction_email" placeholder="Email (optional)"><textarea name="correction_message" required placeholder="What should be corrected?"></textarea><button type="submit">Send correction</button></form><?php endif;?></section>
<?php if($story['sources']):?><div class="sources"><strong>Sources / references</strong><br><br><?=e($story['sources'])?></div><?php endif;?>
<?php if(!empty($story['image_path'])):?><img class="story-cover" src="<?=BASE_URL?>/<?=e($story['image_path'])?>" alt="<?=e($story['title'])?>"><?php endif;?></article>
   
    <?php require __DIR__.'/includes/public-footer.php'; ?>
        
        
        
        <script>document.getElementById('copy-link').addEventListener('click',function(){var button=this,shareUrl=<?=json_encode($shareUrl,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;function copied(){button.textContent='Link copied';window.setTimeout(function(){button.textContent='Copy link'},1800)}function fallbackCopy(){var field=document.createElement('textarea');field.value=shareUrl;field.setAttribute('readonly','');field.style.position='fixed';field.style.opacity='0';document.body.appendChild(field);field.select();var success=document.execCommand('copy');document.body.removeChild(field);if(success){copied()}else{window.prompt('Copy this story link:',shareUrl)}}if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(shareUrl).then(copied).catch(fallbackCopy)}else{fallbackCopy()}});</script></body></html>